name: "🎯 Epic"
description: "Описывает крупную функциональность, состоящую из нескольких features"
title: "[Epic]: "
labels: ["type: epic", "status: needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## 🎯 Описание Epic
        Используйте этот шаблон для описания крупных функциональностей, которые требуют реализации нескольких features.

  - type: textarea
    id: business-goal
    attributes:
      label: "🎯 Бизнес-цель"
      description: "Какую проблему решает эта функциональность? Какие потребности пользователей закрывает?"
      placeholder: "Пользователи должны иметь возможность..."
    validations:
      required: true

  - type: textarea
    id: success-metrics
    attributes:
      label: "📊 Метрики успеха"
      description: "Как мы поймем, что Epic успешно реализована?"
      placeholder: |
        - 95% пользователей используют новую функциональность
        - Уменьшение времени выполнения операции на 30%
        - Отсутствие ошибок в логах

  - type: checkboxes
    id: scope
    attributes:
      label: "📋 Основные компоненты Epic"
      description: "Отметьте основные features, которые входят в эту Epic"
      options:
        - label: "Бэкенд API"
        - label: "Админ-панель"
        - label: "Интеграции с внешними сервисами"
        - label: "Тестирование"
        - label: "Документация"

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: "✅ Критерии приемки"
      description: "Общие критерии, которые должны быть выполнены для всей Epic"
      placeholder: |
        - [ ] Все features работают вместе без конфликтов
        - [ ] Документация обновлена
        - [ ] Произведено тестирование на staging

  - type: input
    id: deadline
    attributes:
      label: "⏰ Желаемый срок"
      description: "Предполагаемая дата завершения (опционально)"
      placeholder: "2025-12-31"

  - type: markdown
    attributes:
      value: |
        ## 🏷️ Дополнительная информация

  - type: dropdown
    id: priority
    attributes:
      label: "🚀 Приоритет"
      description: "Приоритет реализации Epic"
      options:
        - "High (Блокирующий)"
        - "Medium (Важный)"
        - "Low (По возможности)"
    validations:
      required: true

  - type: input
    id: depends-on
    attributes:
      label: "⛓️ Зависит от"
      description: "Номера issues/Epic, от которых зависит эта работа"
      placeholder: "#123, #456"