name: "✨ Feature"
description: "Отдельная функциональность, являющаяся частью Epic"
title: "[Feature]: "
labels: ["type: feature", "status: needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## ✨ Описание Feature
        Используйте этот шаблон для отдельных функциональностей, которые являются частью Epic.

  - type: input
    id: epic-link
    attributes:
      label: "🎯 Связанная Epic"
      description: "Номер Epic issue, к которой относится эта feature"
      placeholder: "#45"
    validations:
      required: true

  - type: textarea
    id: feature-description
    attributes:
      label: "📖 Описание функциональности"
      description: "Детальное описание того, что должно быть реализовано"
      placeholder: "Эта feature позволяет пользователям..."
    validations:
      required: true

  - type: textarea
    id: technical-requirements
    attributes:
      label: "⚙️ Технические требования"
      description: "Технические детали реализации"
      placeholder: |
        - Новая функциональность
        - Изменения в модели данных
        - Миграция данных

  - type: textarea
    id: tasks-breakdown
    attributes:
      label: "🔨 Разбивка на задачи"
      description: "Список конкретных задач для реализации этой feature"
      placeholder: |
        - [ ] Создать модель данных
        - [ ] Реализовать API endpoints
        - [ ] Добавить валидацию
        - [ ] Написать тесты
        - [ ] Обновить документацию

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: "✅ Критерии приемки"
      description: "Конкретные условия, которые должны быть выполнены"
      placeholder: |
        - [ ] API возвращает корректные данные
        - [ ] Обработка ошибок работает правильно
        - [ ] Тесты покрывают 90% кода

  - type: markdown
    attributes:
      value: |
        ## 🏷️ Дополнительная информация

  - type: dropdown
    id: priority
    attributes:
      label: "🚀 Приоритет"
      options:
        - "High (Блокирующий)"
        - "Medium (Важный)"
        - "Low (По возможности)"
    validations:
      required: true

  - type: input
    id: depends-on
    attributes:
      label: "⛓️ Зависит от"
      description: "Номера issues, от которых зависит эта feature"
      placeholder: "#50, #51"